version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: "/src/Geospatial.Grpc"
    schedule:
      interval: weekly
    groups:
      nuget-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: "/examples/python"
    schedule:
      interval: weekly
    groups:
      pip-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/examples/javascript"
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
